# Site settings
title: Berriart | Desarrollo web con software libre
email: alberto@berriart.com
author:
  twitter: artberri
description: Personal page of Alberto Varela a Full Stack Web Developer based in Bilbao.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.berriart.com" # the base hostname & protocol for your site
main_navigation:
- text: Home
  url: /
- text: Projects
  url: /projects/
- text: Blog
  url: /blog/
- text: About me
  url: /alberto-varela/
permalink: /blog/:year/:month/:title/
paginate: 10
paginate_path: "/blog/page:num/"
twitter_username: artberri

# Build settings
markdown: kramdown

exclude: [
    'berriart-foundation',
    'javascript',
    'vendor',
    'bower_components',
    'node_modules',
    'Gruntfile.js',
    'Gemfile',
    'Gemfile.lock',
    'bower.json',
    'package.json',
    'scripts',
    'Rakefile',
    'Readme.md',
    '.scss-lint.yml',
    'eslint.json'
]

sass:
    style: compressed

assets:
  compress:
    css: true
    js: false
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"

responsive_image:
  template: _includes/responsive-image.html
  default_quality: 85
  sizes:
    - width: 870
    - width: 640
    - width: 480
    - width: 320
  base_path: images
  output_path_format: images/resized/%{dirname}/%{width}.%{basename}

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-assets
  - jekyll-responsive-image
