baseURL = "https://www.berriart.com/"
languageCode = "en"
title = "Berriart"
theme = "berriart2022"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
googleAnalytics = "UA-2004323-1"
disqusShortname = "berriart"
pygmentsUseClasses = true

[permalinks]
    blog = "/:section/:year/:month/:slug/"
    pages = "/:slug/"

[sitemap]
    changefreq = "monthly"
    filename = "sitemap.xml"
    priority = 0.5

[params]
    author = "Alberto Varela"
    description = "Personal page of Alberto Varela a Full Stack Web Developer based in Bilbao."
    favicon = "favicon.ico"

[author]
    name = "Alberto Varela"
    twitter = "artberri"

[privacy]
    [privacy.disqus]
        disable = false
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = false
        respectDoNotTrack = true
        useSessionStorage = true
    [privacy.instagram]
        disable = false
        simple = true
    [privacy.twitter]
        disable = false
        enableDNT = true
        simple = true
    [privacy.vimeo]
        disable = false
        simple = true
    [privacy.youtube]
        disable = false
        privacyEnhanced = true

[build]
  writeStats = true
