[[redirects]]
  from = "https://berriart.com/*"
  to = "https://www.albertovarela.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.berriart.com/*"
  to = "https://www.albertovarela.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/alberto-varela/"
  to = "/about-me/"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=365000000, immutable"
