defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:16.15.1-browsers

version: 2
jobs:
  deps:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - pnpm-dependencies-{{ checksum "pnpm-lock.yaml" }}
            # fallback to using the latest cache if no exact match is found
            - pnpm-dependencies-

      - run: npm install -g pnpm
      - run: pnpm i --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: pnpm-dependencies-{{ checksum "pnpm-lock.yaml" }}

      - persist_to_workspace:
          root: ./
          paths:
            - archetypes
            - config.toml
            - content
            - deploy.js
            - node_modules
            - package.json
            - pnpm-lock.yaml
            - postcss.config.js
            - static
            - themes

  build:
    <<: *defaults
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ./

      - run:
          name: build project
          command: hugo

      - persist_to_workspace:
          root: ./
          paths:
            - public

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ./

      # Download and cache dependencies
      - restore_cache:
          keys:
            - pnpm-dependencies-{{ checksum "pnpm-lock.yaml" }}
            # fallback to using the latest cache if no exact match is found
            - pnpm-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: pnpm-dependencies-{{ checksum "pnpm-lock.yaml" }}

      - add_ssh_keys:
          fingerprints:
            - "08:4f:f7:d8:18:12:4b:3a:47:cb:1a:71:3d:f0:be:63"

      - deploy:
          command: npm run deploy

workflows:
  version: 2

  build-deploy:
    jobs:
      - deps
      - build:
          requires:
            - deps
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
