version: '2.1'
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - node/install:
          node-version: '16.15'

      # Download and cache dependencies
      - restore_cache:
          keys:
            - pnpm-dependencies-{{ checksum "pnpm-lock.yaml" }}
            # fallback to using the latest cache if no exact match is found
            - pnpm-dependencies-

      - run:
          name: install pnpm
          command: npm install -g pnpm
      - run:
          name: install dependencies
          command: pnpm i --frozen-lockfile
      - run:
          name: build project
          command: hugo

      - save_cache:
          paths:
            - node_modules
          key: pnpm-dependencies-{{ checksum "pnpm-lock.yaml" }}

      - persist_to_workspace:
          root: ./
          paths:
            - deploy.js
            - node_modules
            - package.json
            - pnpm-lock.yaml
            - public

  deploy:
    docker:
      - image: cimg/node:16.15.1
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ./

      - run:
          name: install pnpm
          command: npm install -g pnpm

      - add_ssh_keys:
          fingerprints:
            - "08:4f:f7:d8:18:12:4b:3a:47:cb:1a:71:3d:f0:be:63"

      - deploy:
          command: pnpm run deploy

workflows:
  version: 2

  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
