defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/ruby:2.4.1-node-browsers

version: 2
jobs:
  lint:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --with=development --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run: sudo npm install -g grunt-cli && npm install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package-lock.json" }}

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run: bundle exec rake lint

      - persist_to_workspace:
          root: ./
          paths:
            - vendor
            - node_modules

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ./

      - run: sudo npm install -g grunt-cli

      - run:
          name: build project
          command: bundle exec rake build

      - persist_to_workspace:
          root: ./
          paths:
            - _site
            - vendor
            - node_modules

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ./

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --with=development --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run: bundle exec rake test

workflows:
  version: 2

  lint-build-test-deploy:
    jobs:
      - lint
      - build
      - test:
          requires:
            - build
