defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/ruby:2.4.1-node-browsers

version: 2
jobs:
  lint:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --with=development --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run: sudo npm install -g grunt-cli
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package-lock.json" }}

      - run: bundle exec rake lint

  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --with=development --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run: sudo npm install -g grunt-cli
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: build project
          command: bundle exec rake build

      - persist_to_workspace:
          root: ./
          paths:
            - _site

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ./

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --with=development --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run: bundle exec rake test

      - persist_to_workspace:
          root: ./
          paths:
            - _site

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ./

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run: sudo npm install -g grunt-cli
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package-lock.json" }}

      - add_ssh_keys:
          fingerprints:
            - "08:4f:f7:d8:18:12:4b:3a:47:cb:1a:71:3d:f0:be:63"

      - deploy:
          command: grunt deploy

workflows:
  version: 2

  lint-build-test-deploy:
    jobs:
      - lint
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - lint
            - test
