defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:16.2-browsers

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - npm-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - npm-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: npm-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: build project
          command: npm run build

      - persist_to_workspace:
          root: ./
          paths:
            - archetypes
            - config.toml
            - content
            - layouts
            - themes

  release:
    <<: *defaults
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ./

      - run:
          name: release project
          command: hugo

      - persist_to_workspace:
          root: ./
          paths:
            - public

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ./

      # Download and cache dependencies
      - restore_cache:
          keys:
            - npm-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - npm-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: npm-dependencies-{{ checksum "package-lock.json" }}

      - add_ssh_keys:
          fingerprints:
            - "08:4f:f7:d8:18:12:4b:3a:47:cb:1a:71:3d:f0:be:63"

      - deploy:
          command: npm run deploy

workflows:
  version: 2

  build-deploy:
    jobs:
      - build
      - release:
          requires:
            - build
      - deploy:
          requires:
            - release
          filters:
            branches:
              only: master
